### ISSUE TITLE
can not run the Endless Tunnel according to codelabs

### ISSUE THREAD

**Issue by bingowang1991** [android/ndk-samples#792] opened 2021-04-19 02:16 UTC
i am doing the work according to codelabs,but it is not do not work because 

> Task :app:externalNativeBuildDebug FAILED
Build game_arm64-v8a
ninja: Entering directory `D:\work\EndlessTunnel\app\.cxx\cmake\debug\arm64-v8a'
[1/2] Linking CXX static library glm\libglm.a
FAILED: glm/libglm.a 
cmd.exe /C "cd . && D:\work\androidSDK\cmake\3.10.2.4988404\bin\cmake.exe -E remove glm\libglm.a && D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe qc glm\libglm.a  glm/CMakeFiles/glm.dir/detail/glm.cpp.o && D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe glm\libglm.a && cd ."
D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe: unable to rename 'glm\libglm.a'; reason: Permission denied
ninja: build stopped: subcommand failed.

Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process D:\work\androidSDK\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\work\EndlessTunnel\app\.cxx\cmake\debug\arm64-v8a game}
  ninja: Entering directory `D:\work\EndlessTunnel\app\.cxx\cmake\debug\arm64-v8a'
  [1/2] Linking CXX static library glm\libglm.a
  FAILED: glm/libglm.a 
  cmd.exe /C "cd . && D:\work\androidSDK\cmake\3.10.2.4988404\bin\cmake.exe -E remove glm\libglm.a && D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ar.exe qc glm\libglm.a  glm/CMakeFiles/glm.dir/detail/glm.cpp.o && D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe glm\libglm.a && cd ."
  D:\work\androidSDK\ndk\21.2.6472646\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android-ranlib.exe: unable to rename 'glm\libglm.a'; reason: Permission denied
  ninja: build stopped: subcommand failed.

**Comment by natetrost** [comment] 2021-04-19 20:29
I've tried a few different ways to reproduce this issue without success using Android Studio 4.1.3 running on Windows 10.

Does this issue occur if you try building the project immediately after importing the sample, but before doing any of the Codelab steps?

Which version of Android Studio, Android Build Tools and Android Platform Tools are you using?

Nate Trost
Developer Relations Engineer, Android Games @ Google

**Comment by bingowang1991** [comment] 2021-04-20 02:50
Does this issue occur if you try building the project immediately after importing the sample, but before doing any of the Codelab steps?
// no, sync the sample project is successfully, but when i had build the project or run the project, it occur this issue（i am doing the codelabs: Getting set up
codelabs:
https://developer.android.com/codelabs/android-performance-tuner-native#1）.

Android Studio version: 4.1.3

Changing the API levels
To change the API level for the app, do the following:

the codelab steps:
Open the app build.gradle file (if it is not still open).
Find the line containing minSdkVersion and change it from 14 to 24.
Find the line containing targetSdkVersion and change it from 28 to 29.
Save the file.
Sync the project. Click File > Sync Project with Gradle Files.

1）cmake\3.10.2.4988404
2）ndk：21.2.6472646

thank you very much.

**Comment by ggfan** [comment] 2021-04-20 05:14
Tried with the given environment, could not see the reported problem: it could be some difference between your windows and my windows environment. You might be able to help to root cause/narrow down the issue with step by step updating the project, after each step(or a sub-step), sync the project, clean, and rebuild, for example:

1. import the project either by studio's "import sample" option, or cloning the repo and "open the existing project" option
2. build and run the project (I ran it on Pixel device with Android 12 preview on it)
3. update the build script to 4.1.3 (you will be prompted to update gradle version in IDE), clean and rebuild.
4. update minSdkVersion and targetSdkVersion,  clean and rebuild
5. clean the project, then update the package name in the mentioned 2 places(however, I personally use studio's refactor to change it in everywhere, including studio's caches, comments. But it is not perfect, the one in build.gradle might get messed up, I have to fix it up), build again
6. add other changes for the xml file (internet usage, clearTextTraffic etc). clean and build again

hopefully along the way we get to know which step triggers the issue.
your ndk is at D:\work\androidSDK\ndk\21.2.*\, correct?

**Comment by bingowang1991** [comment] 2021-04-20 06:38
yes, my ndk is at D:\work\androidSDK\ndk\21.2.*.
my window computer os is 10.
do you want any other information for this?

**Comment by ggfan** [comment] 2021-04-20 17:54
@bingowang1991 yeah, need you help to see if it is environment problem or really the code issue. Could you follow 
https://github.com/android/ndk-samples/issues/792#issuecomment-822979009 and update at which step you encounter the issue?

Nate and I could not see the problem, need more narrow down from your side. Thank you.

**Comment by bingowang1991** [comment] 2021-04-21 09:55
1. import the project either by studio's "import sample" option, or cloning the repo and "open the existing project" option
// ok
2.build and run the project (I ran it on Pixel device with Android 12 preview on it)
// no, when i build, it occur this issue.

**Comment by bingowang1991** [comment] 2021-04-21 09:55
i can sync this project, but i can not build this.

**Comment by bingowang1991** [comment] 2021-04-21 14:52
when i execute this command, it occur this issuse:
D:\work\EndlessTunnel\app\.cxx\cmake\debug\armeabi-v7a>D:\work\androidSDK\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ar.exe qc glm\libglm.a glm\CMakeFiles\glm.dir\detail\glm.cpp.o
D:\work\androidSDK\ndk\21.3.6528147\toolchains\llvm\prebuilt\windows-x86_64\bin\arm-linux-androideabi-ar.exe: unable to rename 'glm\libglm.a'; reason: Permission denied

**Comment by ggfan** [comment] 2021-04-21 16:10
thank you. now we know that this is happening from the source right out of the repo, we could do more debugging.

first I got no clue about this issue you are seeing, we will have to do some guessing.
could you check what the access right for the file glm\CMakeFiles\glm.dir\detail\glm.cpp.o? the ar tool is just combining the object files if there are many, for this case only one file glb.cpp.o --> libglm.a, so it is a rename. could you check whether ./app/.cxx/cmake/debug/armeabi-v7a/glm(translate this to windows format) is there?

looks like you have the file of glm\CMakeFiles\glm.dir\detail\glm.cpp.o built out, this file is read-only(protected)? or the target directory is not there 'glm' directory is protected.

This is some tedious debugging, heavily depends on your environment and your user privilege(I run it with admin right on windows) on the machine, my guess. Please let us know.

**Comment by bingowang1991** [comment] 2021-04-22 11:46
maybe i think my android studio permission is Insufficient.
do you know how to set the androidstudio>?

**Comment by ggfan** [comment] 2021-04-27 18:00
when you login to your windows computer, you are login as admin, correct?

**Comment by ggfan** [comment] 2021-05-24 20:42
closing this one for now: feel free to re-open if you still have the problem.

**Closed by ggfan** 2021-05-24 20:42 UTC
