### ISSUE TITLE
native-activity crashes on launch

### ISSUE THREAD

**Issue by Callum5042** [android/ndk-samples#967] opened 2023-11-25 16:11 UTC
native-activity example crashes when launched. Changing the 'AndroidManifest.xml' to remove the line 'android:hasCode="false"' seems to fix it. Would be nice to have it work by without having to try debug it for other people who are looking at these examples

**Comment by DanAlbert** [comment] 2024-05-03 21:28
Duplicate of #929

**Closed by DanAlbert** 2024-05-03 21:28 UTC
