### ISSUE TITLE
how can i make a .a file into aar prefab offered  by none current building?

### ISSUE THREAD

**Issue by oobask** [android/ndk-samples#764] opened 2020-11-14 11:07 UTC
ref your simple
[prefab-dependency](https://github.com/android/ndk-samples/tree/main/prefab/prefab-dependency)  

how can i do this!

**Comment by ggfan** [comment] 2020-11-16 18:59
you mean how to publish your library in an AAR? you might look at the the [prefab-publishing](https://github.com/android/ndk-samples/tree/main/prefab/prefab-publishing) sample, and [the official documentation](https://developer.android.com/studio/build/native-dependencies?hl=de&buildsystem=cmake&agpversion=4.1).

**Comment by Efaker** [comment] 2020-11-17 04:10
> you mean how to publish your library in an AAR? you might look at the the [prefab-publishing](https://github.com/android/ndk-samples/tree/main/prefab/prefab-publishing) sample, and [the official documentation](https://developer.android.com/studio/build/native-dependencies?hl=de&buildsystem=cmake&agpversion=4.1).

I hava run the demo prefab-publishing,But cant make a ref .a file none this build coversation to aar!

**Comment by Efaker** [comment] 2020-11-17 04:19
`add_library(libtool STATIC IMPORTED)
set_target_properties(libtool PROPERTIES IMPORTED_LOCATION  ${CMAKE_SOURCE_DIR}/libs/${ANDROID_ABI}/libtool.a)
file(GLOB native_srcc "${CMAKE_SOURCE_DIR}/*.cpp")

add_library(
        native-lib
        STATIC
        ${native_srcc}
        ${Scaffolding}
        )
target_link_libraries(
        native-lib
        libtool
        android
        z
        log)`


## like this code 'native-lib.a' can build in arr but  the 'libtool.a ' left! the aar cant use

**Comment by ggfan** [comment] 2020-11-18 00:17
you do not need to pack libtool.a, because static lib pulls in all needed code into the final static native-lib already.

for shared lib though, "[Each Module has its own headers and at most one library per target platform.](https://google.github.io/prefab/)" as documented in the wiki page, "Package Structure" section.  To workaround this you will need to do one of followings:
  - make 2 AARs ( one for each shared lib.  For the libraries that you only have binaries, you could NOT use prefab to generate AAR, but [ndkport](https://android.googlesource.com/platform/tools/ndkports/) or other tools, or even manually pack an AAR, AAR is just a zip file ).
 - make 2 modules inside the one AAR: you have to use ndkport or other tools to do packing.

may you check it out?

**Comment by Efaker** [comment] 2020-11-18 04:24
Did you sure head line ? As a matter of fact, native-lib.a just contains the code `${native_srcc}
${Scaffolding}` has no 'libtool.a'!

**Comment by ggfan** [comment] 2020-11-18 13:56
https://softwareengineering.stackexchange.com/questions/211999/are-nested-static-library-dependencies-possible
static libs are just object files, when you give them as input as dependency, they just get "treated" as object files and merged to the final static lib.  No need to distribute the libtool.a lib to your client anymore.

you might give it a try.

**Comment by ggfan** [comment] 2020-11-18 15:47
Adding @DanAlbert to the thread.

Actually I am not sure: I tried, and you are right, the static lib's object code are *not* combined into native-lib.a.  For static libraries, target_link_libraries() has no use since there is no link stage at all.

Now coming back to the original question:  yeah you will have to distribute the original static lib ( [unless you combine the libs](https://stackoverflow.com/questions/50022318/using-cmake-to-build-a-static-library-of-static-libraries)). 

Then it falls into the same track as the shared libs path: the current implementation will not help for that, [filed a bug](https://issuetracker.google.com/issues/173551290) to track it: technically every add_library() statement inside the CMakeLists.txt should be able to be added, as a module, to the same AAR; I agree with you on the fact that I like to avoid using many different tools to do the similar work, and if I have IDE open, I like to finish all of work inside IDE.

let's track it from [that bug](https://issuetracker.google.com/issues/173551290). For now, looks like that you will have to workaround it with manual way for imported libraries.

**Comment by Efaker** [comment] 2020-11-18 16:01
Aha. So pride of agreement with Google Android team members! I feel im flying now!

**Comment by ggfan** [comment] 2020-11-18 19:27
@Efaker ,  please add your input to [that bug](https://issuetracker.google.com/issues/173551290) to make sure they are considered, and keep track on that one: this one will be closed soon if no objections.  I will update the official documentation to reflect the what the current expected behaviors are.

**Closed** 2024-05-03 22:45 UTC
