### ISSUE TITLE
Native Activity(NDK) sample app crashed with  RuntimeException and  ClassNotFoundException while deploying the app

### ISSUE THREAD

**Issue by LaxmanDroid** [android/ndk-samples#978] opened 2024-01-11 05:52 UTC
```
Process: com.example.native_activity, PID: 16011
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~3qoxyJB8dcEurYEw244CSw==/com.example.native_activity-JdNJmuJoyIXaEFroweP_bw==/lib/x86_64, /data/app/~~3qoxyJB8dcEurYEw244CSw==/com.example.native_activity-JdNJmuJoyIXaEFroweP_bw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:7770)
                                                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276)
                                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983)
                                                                                                        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                        at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                        at android.os.Looper.loop(Looper.java:294)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~3qoxyJB8dcEurYEw244CSw==/com.example.native_activity-JdNJmuJoyIXaEFroweP_bw==/lib/x86_64, /data/app/~~3qoxyJB8dcEurYEw244CSw==/com.example.native_activity-JdNJmuJoyIXaEFroweP_bw==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
                                                                                                        at android.app.ActivityThread.installProvider(ActivityThread.java:7754)
                                                                                                        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7276) 
                                                                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6983) 
                                                                                                        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2236) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                        at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                        at android.os.Looper.loop(Looper.java:294) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971) 

1. > ``
```

**Comment by BaiLenye** [comment] 2024-01-17 08:29
I also encountered this problem

**Comment by tmt05351** [comment] 2024-03-26 05:10
https://github.com/android/ndk-samples/issues/929

**Comment by DanAlbert** [comment] 2024-05-03 21:27
Duplicate of #929

(yes, I know the dup is technically the other way around, but that one has all the discussion, it's fixed now anyway)

**Closed by DanAlbert** 2024-05-03 21:27 UTC
