### ISSUE TITLE
Getting ClassNotFoundException on while running Native Activity[NDK] sample app 

### ISSUE THREAD

**Issue by Laxmaandroid** [android/ndk-samples#934] opened 2023-03-24 09:04 UTC
Steps to Reproduce:
1. Open android studio
2. Import sample app named, **Native Activity** under NDK category
3. Select any device and run the app in it

Actual:

I saw below exception while deploying the app

![Screenshot from 2023-03-23 14-29-32](https://user-images.githubusercontent.com/105067989/227473745-f9ecc795-ba18-41e9-99c9-3fea98e9d228.png)

FATAL EXCEPTION: main
                                                                                                    Process: com.example.native_activity, PID: 30149
                                                                                                    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~DnDZG8k__rEJWZz3bJMAzA==/com.example.native_activity-n6Xs1BfFs5pShMl0smhnEw==/lib/arm64, /data/app/~~DnDZG8k__rEJWZz3bJMAzA==/com.example.native_activity-n6Xs1BfFs5pShMl0smhnEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.startup.InitializationProvider" on path: DexPathList[[],nativeLibraryDirectories=[/data/app/~~DnDZG8k__rEJWZz3bJMAzA==/com.example.native_activity-n6Xs1BfFs5pShMl0smhnEw==/lib/arm64, /data/app/~~DnDZG8k__rEJWZz3bJMAzA==/com.example.native_activity-n6Xs1BfFs5pShMl0smhnEw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8296)

**Comment by BenShen98** [comment] 2023-04-13 10:41
I am also getting the same issue.

With `Android Studio Electric Eel | 2022.1.1 Patch 2` and commit `eb8c57aaf8e4e8da8debfe7a6f44149630ac775e` (main branch)

**Comment by BenShen98** [comment] 2023-04-13 10:46
FIY #929 https://github.com/android/ndk-samples/issues/929#issuecomment-1423506761 provides a soultion to this.

**Comment by novikovag** [comment] 2023-06-07 22:47
> ```diff
> androidx.startup.InitializationProvider
> ```

IDE show error:

Class referenced in the manifest, androidx.startup.InitializationProvider, was not found in the project or the libraries
Unresolved class 'InitializationProvider'

**Comment by novikovag** [comment] 2023-06-07 22:49
> FIY [#929 (comment)](https://github.com/android/ndk-samples/issues/929#issuecomment-1423506761) provides a soultion to this.
> 
> ```diff
> diff --git a/native-activity/app/src/main/AndroidManifest.xml b/native-activity/app/src/main/AndroidManifest.xml
> index 8698411..0b3175c 100644
> --- a/native-activity/app/src/main/AndroidManifest.xml
> +++ b/native-activity/app/src/main/AndroidManifest.xml
> @@ -1,6 +1,7 @@
>  <?xml version="1.0" encoding="utf-8"?>
>  
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> +    xmlns:tools="http://schemas.android.com/tools"
>      android:versionCode="1"
>            android:versionName="1.0">
> 
> @@ -12,6 +13,10 @@
>        android:label="@string/app_name"
>        android:hasCode="false">
> 
> +    <provider android:name="androidx.startup.InitializationProvider"
> +        android:authorities="${applicationId}.androidx-startup"
> +        tools:node="remove" />
> +
>      
>      <activity android:name="android.app.NativeActivity"
> ```

IDE show error:

Class referenced in the manifest, androidx.startup.InitializationProvider, was not found in the project or the libraries
Unresolved class 'InitializationProvider'

**Comment by 554512097** [comment] 2023-09-13 03:26
yes!

**Comment by dingsijie-nreal** [comment] 2023-12-21 08:00
same here, BenShen98's reply works for me. Though the link[#929 (comment)](https://github.com/android/ndk-samples/issues/929#issuecomment-1423506761) seems broken...
> FIY [#929 (comment)](https://github.com/android/ndk-samples/issues/929#issuecomment-1423506761) provides a soultion to this.
> 
> ```diff
> diff --git a/native-activity/app/src/main/AndroidManifest.xml b/native-activity/app/src/main/AndroidManifest.xml
> index 8698411..0b3175c 100644
> --- a/native-activity/app/src/main/AndroidManifest.xml
> +++ b/native-activity/app/src/main/AndroidManifest.xml
> @@ -1,6 +1,7 @@
>  <?xml version="1.0" encoding="utf-8"?>
>  
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> +    xmlns:tools="http://schemas.android.com/tools"
>      android:versionCode="1"
>            android:versionName="1.0">
> 
> @@ -12,6 +13,10 @@
>        android:label="@string/app_name"
>        android:hasCode="false">
> 
> +    <provider android:name="androidx.startup.InitializationProvider"
> +        android:authorities="${applicationId}.androidx-startup"
> +        tools:node="remove" />
> +
>      
>      <activity android:name="android.app.NativeActivity"
> ```

well, it worke

**Comment by DanAlbert** [comment] 2024-05-03 21:48
Duplicate of #929

**Closed by DanAlbert** 2024-05-03 21:48 UTC
